# Generated by Django 3.0.6 on 2022-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Czy zamówienie zostało zrealizowane?'),
        ),
    ]
