# Generated by Django 3.0.6 on 2022-03-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0003_auto_20220319_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(verbose_name='Czas wykonania (min.)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(verbose_name='Cena (zł)'),
        ),
    ]
