# Generated by Django 3.0.6 on 2022-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0004_auto_20220321_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meeting_date',
            field=models.DateTimeField(),
        ),
    ]
