# Generated by Django 3.0.6 on 2022-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0005_auto_20220323_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateField(),
        ),
    ]
