# Generated by Django 3.0.6 on 2022-03-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0006_auto_20220323_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='autodetailing_app.Worker'),
        ),
    ]
