# Generated by Django 3.0.6 on 2022-03-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0007_auto_20220324_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
