# Generated by Django 3.0.6 on 2022-03-29 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0008_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='cart',
            name='meeting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='services',
            field=models.ManyToManyField(to='autodetailing_app.Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='meeting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(to='autodetailing_app.Service'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='worker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autodetailing_app.Worker'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autodetailing_app.Worker'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Czas wykonania (min.)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Dodaj plik'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0, verbose_name='Cena (zł)'),
        ),
    ]
