# Generated by Django 3.0.6 on 2022-03-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0009_auto_20220325_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='termin_realizacji',
            new_name='meeting_date',
        ),
    ]
