# Generated by Django 3.0.6 on 2022-03-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodetailing_app', '0010_auto_20220325_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meeting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='worker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autodetailing_app.Worker'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Czas wykonania (min.)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0, verbose_name='Cena (zł)'),
        ),
    ]
